# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5891f3a383465683ecc59b5b045a76340642473b730916ffc5f5d4955108883aa8c11a803422276d2599c8e582442e55dc167790b19cf50c311439e5dcd3b28

test:
  secret_key_base: 007721bdaefb4ec2c0da54dba4c09183c9ba39b361b9c04f866c2ff763f10171e6a70ea3185dd96883499a8630d966ffe010ed04b71ad2a61bdcdc4b543865f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
